---
apiVersion: v1
kind: Namespace
metadata:
  name: ip2country
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip2country-deployment
  namespace: ip2country
spec:
  selector:
    matchLabels:
      app: ip2country
  replicas: 2
  template:
    metadata:
      labels:
        app: ip2country
    spec:
      containers:
        - name: ip2country
          image: extrawurst/ip2country
          ports:
            - containerPort: 5000
          env:
            - name: RUST_LOG
              value: info
---
apiVersion: v1
kind: Service
metadata:
  name: ip2country-externalaccess
  namespace: ip2country
spec:
  selector:
    app: ip2country
  ports:
    - name: externalaccessapi
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: NodePort
---
