[package]
name = "ip2country-bench"
version = "0.1.0"
authors = ["Stephan Dilly <dilly.stephan@gmail.com>"]
edition = "2018"

[dependencies]
ip2country = { path = "../ip2country" }

[dev-dependencies]
iai = "0.1"

[[bench]]
name = "benchmark"
harness = false