name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      run: |
        docker login \
        -u ${{ secrets.DOCKER_USERNAME }} \
        -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t extrawurst/ip2country:latest -f Dockerfile .

    - name: Publish Docker image
      run: docker push extrawurst/ip2country