name: Publish Docker
on:
  push:
    branches: [ '*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: check
      run: make check

    - name: benchmark-iai
      run: cd ip2country-bench && make bench-inside-docker
    
    - name: benchmark
      run: cargo bench